// ignore_for_file: file_names

const Map<String, List<List<String>>> subjectVideoUrls = {
  '국어': [
    ['https://www.youtube.com/watch?v=kkMZSE9x90E', '이지영'],
    ['https://www.youtube.com/watch?v=-Q7U_9wabNM', '테디'],
    ['https://www.youtube.com/watch?v=XQzdkDCaIuA', '범작가'],
    ['https://www.youtube.com/watch?v=CLdhfNNkIcI', '두니'],
    ['https://www.youtube.com/watch?v=QCkz0_biQ_k', '심찬우'],
    ['https://www.youtube.com/watch?v=1_DqPYFbUTo', '김동욱'],
    ['https://www.youtube.com/watch?v=_FHDcl2tDjY', '범작가'],
    ['https://www.youtube.com/watch?v=TAmr_TXb-94', '심찬우'],
  ],
  '수학': [
    ['https://www.youtube.com/watch?v=RmcBsyO7iJ8', '한상우'],
    ['https://www.youtube.com/watch?v=LS8xXMLdLe4', '한상우'],
    ['https://www.youtube.com/watch?v=c1RqFsixUVk', '한상우'],
    ['https://www.youtube.com/watch?v=PcqGH4vEpww', '김지석'],
    ['https://www.youtube.com/watch?v=J3IvYwqZxRw', '김지석'],
    ['https://www.youtube.com/watch?v=cQkAQOzIz_s', '김지석'],
    ['https://www.youtube.com/watch?v=l6I1g-Z1Jmg', '김소이'],
    ['https://www.youtube.com/watch?v=1NSXi66ip20', '김소이'],
    ['https://www.youtube.com/watch?v=FVB9Hg3jpbQ', '서울대쌍둥이(여호원, 여호용)'],
    ['https://www.youtube.com/watch?v=wlz1VmsgR00', '서울대쌍둥이(여호원, 여호용)'],
    ['https://www.youtube.com/watch?v=_FHDcl2tDjY', '범작가'],
    ['https://www.youtube.com/watch?v=TAmr_TXb-94', '심찬우'],
  ],
  '영어': [
    ['https://www.youtube.com/watch?v=Mhg3mJiNi3c', '조정식'],
    ['https://www.youtube.com/watch?v=EBw8rz5XHQc', '이명학'],
    ['https://www.youtube.com/watch?v=Z6-i2F6BDeQ', '김기철'],
    ['https://www.youtube.com/watch?v=XRnXEoNHZt0', '김지영'],
  ],
  '사회탐구': [
    ['https://www.youtube.com/watch?v=QttltWXejQ0', '강사 이름 없음'],
    ['https://www.youtube.com/watch?v=xmCN_lWj9zI', '강사 이름 없음'],
    ['https://www.youtube.com/watch?v=jnIOGTPjMck', '강사 이름 없음'],
    ['https://www.youtube.com/watch?v=QiRgANDcoeo', '강사 이름 없음'],
    ['https://www.youtube.com/watch?v=ttsn1A6XxoY', '강사 이름 없음'],
    ['https://www.youtube.com/watch?v=E8jJofeowJo', '강사 이름 없음'],
  ],
  '과학탐구': [
    ['https://www.youtube.com/watch?v=SaMWc630CPw', '이규철'],
    ['https://www.youtube.com/watch?v=Wds2Pju7mTc', '이규철'],
    ['https://www.youtube.com/watch?v=NUxtgicSCcQ', '이규철'],
    ['https://www.youtube.com/watch?v=11hrnOJqLv0', '배기범'],
    ['https://www.youtube.com/watch?v=NImPLLUvy60', '함석진'],
    ['https://www.youtube.com/watch?v=LHwPvvDD70A', '함석진'],
    ['https://www.youtube.com/watch?v=Kjz_irkL-o4', '이훈식'],
    ['https://www.youtube.com/watch?v=wj1xBKrftvQ', '장주희'],
    ['https://www.youtube.com/watch?v=EZsVQboR4u4', '송민준'],
    ['https://www.youtube.com/watch?v=cGfydaMdtYM', '이강희'],
    ['https://www.youtube.com/watch?v=qPhZhfV6W94', '강승훈'],
    ['https://www.youtube.com/watch?v=3ZcCAh3bxBA', '고석용'],
    ['https://www.youtube.com/watch?v=38QzEJpr-dk', '고석용'],
    ['https://www.youtube.com/watch?v=3PFyshTsJGg', '고석용'],
    ['https://www.youtube.com/watch?v=NlWXG200zAU', '조한결'],
    ['https://www.youtube.com/watch?v=-ZSw6T3jc_k', '윤도영'],
    ['https://www.youtube.com/watch?v=K4Tspd_u7RA', '윤도영'],
    ['https://www.youtube.com/watch?v=C81vZrhUWao', '김정호'],
    ['https://www.youtube.com/watch?v=9P_x6GQP4mU', '김정호'],
    ['https://www.youtube.com/watch?v=Pqk1Pkq_VB0', '김정호'],
  ],
  '한국사': [
    ['https://www.youtube.com/watch?v=oLcOhyoFPQg', '최태성'],
    ['https://www.youtube.com/watch?v=83vYsRZ-s7Q', '탁이'],
    ['https://www.youtube.com/watch?v=AXzmDzMuTlM', '최서임'],
  ],
  '공부법': [
    ['https://www.youtube.com/watch?v=TwLBAzhnLoA', '범작가'],
    ['https://www.youtube.com/watch?v=NeuKT9U_a5U', '심찬우'],
    ['https://www.youtube.com/watch?v=qy-Gtj3d_fw', '정종윤'],
    ['https://www.youtube.com/watch?v=qy-Gtj3d_fw', '정종윤'],
    ['https://www.youtube.com/watch?v=UL1o0V9XZgQ', '정종윤'],
    ['https://www.youtube.com/watch?v=pYA4GaUHE_0', '서울대쌍둥이'],
    ['https://www.youtube.com/watch?v=YSRAjQtQVd8', '서울대쌍둥이'],
    ['https://www.youtube.com/watch?v=t49Jq67ae50', '배기범'],
  ],
  '동기부여': [
    ['https://www.youtube.com/watch?v=dE2gzSmUVmU', '전한길'],
    ['https://www.youtube.com/watch?v=t3CryOu1pMU', '전한길'],
    ['https://www.youtube.com/watch?v=0Kij2BdDcio', '정승제'],
    ['https://www.youtube.com/watch?v=UL1o0V9XZgQ', '정종윤'],
  ]
};
